version: '3'

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - ./home:/home/:rw
      - ./nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx/:rw

  # redis:
  #   image: redis:${REDIS_VERSION}
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro