version: '3'

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - ./home:/home/:rw
      - ./nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx/:rw
    restart: always

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data:/var/lib/mysql:rw
      
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  # redis:
  #   image: redis:${REDIS_VERSION}
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro